# data1.py - ULTIMATE SPIDER-MAN DATABASE (Unique Characters Only)

karakterler = [
    # --- HEROES (KAHRAMANLAR & MÜTTEFİKLER) ---
    {"Ad": "Peter Parker", "Cinsiyet": "Male", "Tur": "Mutate", "Tip": "Hero", "Kaynak": "Bite", "Yil": 1962,
     "Comic": "Amazing Fantasy #15"},
    {"Ad": "Miles Morales", "Cinsiyet": "Male", "Tur": "Mutate", "Tip": "Hero", "Kaynak": "Bite", "Yil": 2011,
     "Comic": "Ultimate Fallout #4"},
    {"Ad": "Ghost-Spider (Gwen)", "Cinsiyet": "Female", "Tur": "Mutate", "Tip": "Hero", "Kaynak": "Bite", "Yil": 2014,
     "Comic": "Edge of Spider-Verse #2"},
    {"Ad": "Ben Reilly", "Cinsiyet": "Male", "Tur": "Clone", "Tip": "Hero", "Kaynak": "Science", "Yil": 1975,
     "Comic": "Amazing Spider-Man #149"},
    {"Ad": "Kaine Parker", "Cinsiyet": "Male", "Tur": "Clone", "Tip": "Hero", "Kaynak": "Science", "Yil": 1994,
     "Comic": "Web of Spider-Man #119"},
    {"Ad": "Miguel O'Hara", "Cinsiyet": "Male", "Tur": "Mutate", "Tip": "Hero", "Kaynak": "Science", "Yil": 1992,
     "Comic": "Spider-Man 2099 #1"},
    {"Ad": "Silk (Cindy Moon)", "Cinsiyet": "Female", "Tur": "Mutate", "Tip": "Hero", "Kaynak": "Bite", "Yil": 2014,
     "Comic": "Amazing Spider-Man #1"},
    {"Ad": "Spider-Woman (Jessica)", "Cinsiyet": "Female", "Tur": "Mutate", "Tip": "Hero", "Kaynak": "Science",
     "Yil": 1977, "Comic": "Marvel Spotlight #32"},
    {"Ad": "Black Cat", "Cinsiyet": "Female", "Tur": "Human", "Tip": "Anti-Hero", "Kaynak": "Training", "Yil": 1979,
     "Comic": "Amazing Spider-Man #194"},
    {"Ad": "Silver Sable", "Cinsiyet": "Female", "Tur": "Human", "Tip": "Anti-Hero", "Kaynak": "Training", "Yil": 1985,
     "Comic": "Amazing Spider-Man #265"},
    {"Ad": "Punisher", "Cinsiyet": "Male", "Tur": "Human", "Tip": "Anti-Hero", "Kaynak": "Training", "Yil": 1974,
     "Comic": "Amazing Spider-Man #129"},
    {"Ad": "Daredevil", "Cinsiyet": "Male", "Tur": "Mutate", "Tip": "Hero", "Kaynak": "Accident", "Yil": 1964,
     "Comic": "Daredevil #1"},
    {"Ad": "Agent Venom", "Cinsiyet": "Male", "Tur": "Human", "Tip": "Hero", "Kaynak": "Alien",
     "Yil": 1962, "Comic": "Amazing Fantasy #15"},
    {"Ad": "Spider-Ham", "Cinsiyet": "Male", "Tur": "Animal", "Tip": "Hero", "Kaynak": "Bite", "Yil": 1983,
     "Comic": "Marvel Tails #1"},
    {"Ad": "Spider-Noir", "Cinsiyet": "Male", "Tur": "Mutate", "Tip": "Hero", "Kaynak": "Bite", "Yil": 2009,
     "Comic": "Spider-Man Noir #1"},
    {"Ad": "Peni Parker", "Cinsiyet": "Female", "Tur": "Human", "Tip": "Hero", "Kaynak": "Tech", "Yil": 2014,
     "Comic": "Edge of Spider-Verse #5"},
    {"Ad": "Madame Web (Cassandra)", "Cinsiyet": "Female", "Tur": "Mutant", "Tip": "Hero", "Kaynak": "Genetic",
     "Yil": 1980, "Comic": "Amazing Spider-Man #210"},
    {"Ad": "Anya Corazon", "Cinsiyet": "Female", "Tur": "Mutate", "Tip": "Hero", "Kaynak": "Magic", "Yil": 2004,
     "Comic": "Amazing Fantasy #1"},
    {"Ad": "Toxin", "Cinsiyet": "Male", "Tur": "Symbiote", "Tip": "Anti-Hero", "Kaynak": "Alien", "Yil": 2004,
     "Comic": "Venom/Carnage #2"},
    {"Ad": "Anti-Venom", "Cinsiyet": "Male", "Tur": "Symbiote", "Tip": "Anti-Hero", "Kaynak": "Science", "Yil": 2008,
     "Comic": "Amazing Spider-Man #569"},
    {"Ad": "Spider-Punk", "Cinsiyet": "Male", "Tur": "Mutate", "Tip": "Hero", "Kaynak": "Bite", "Yil": 2015,
     "Comic": "Amazing Spider-Man #10"},
    {"Ad":"Prowler(Aaron Davis)","Cinsiyet":"Male","Tur":"Human","Tip":"Villain","Kaynak":"Tech","Yil":2011,
     "Comic":"Ultimate Comics Spider-Man #1"},
    {"Ad": "Julia Carpenter", "Cinsiyet": "Female", "Tur": "Mutate", "Tip": "Hero", "Kaynak": "Science", "Yil": 1984,
     "Comic": "Secret Wars #6"},

    # --- VILLAINS (KÖTÜLER) ---
    {"Ad": "Green Goblin", "Cinsiyet": "Male", "Tur": "Mutate", "Tip": "Villain", "Kaynak": "Science", "Yil": 1964,
     "Comic": "Amazing Spider-Man #14"},
    {"Ad": "Doctor Octopus", "Cinsiyet": "Male", "Tur": "Human", "Tip": "Villain", "Kaynak": "Accident", "Yil": 1963,
     "Comic": "Amazing Spider-Man #3"},
    {"Ad": "Venom (Eddie)", "Cinsiyet": "Male", "Tur": "Symbiote", "Tip": "Anti-Hero", "Kaynak": "Alien", "Yil": 1988,
     "Comic": "Amazing Spider-Man #300"},
    {"Ad": "Carnage", "Cinsiyet": "Male", "Tur": "Symbiote", "Tip": "Villain", "Kaynak": "Alien", "Yil": 1992,
     "Comic": "Amazing Spider-Man #361"},
    {"Ad": "Mysterio", "Cinsiyet": "Male", "Tur": "Human", "Tip": "Villain", "Kaynak": "Tech", "Yil": 1964,
     "Comic": "Amazing Spider-Man #13"},
    {"Ad": "Kraven the Hunter", "Cinsiyet": "Male", "Tur": "Mutate", "Tip": "Villain", "Kaynak": "Science", "Yil": 1964,
     "Comic": "Amazing Spider-Man #15"},
    {"Ad": "Sandman", "Cinsiyet": "Male", "Tur": "Mutate", "Tip": "Villain", "Kaynak": "Accident", "Yil": 1963,
     "Comic": "Amazing Spider-Man #4"},
    {"Ad": "Electro", "Cinsiyet": "Male", "Tur": "Mutate", "Tip": "Villain", "Kaynak": "Accident", "Yil": 1964,
     "Comic": "Amazing Spider-Man #9"},
    {"Ad": "Vulture", "Cinsiyet": "Male", "Tur": "Human", "Tip": "Villain", "Kaynak": "Tech", "Yil": 1963,
     "Comic": "Amazing Spider-Man #2"},
    {"Ad": "Lizard", "Cinsiyet": "Male", "Tur": "Mutate", "Tip": "Villain", "Kaynak": "Science", "Yil": 1963,
     "Comic": "Amazing Spider-Man #6"},
    {"Ad": "Kingpin", "Cinsiyet": "Male", "Tur": "Human", "Tip": "Villain", "Kaynak": "Training", "Yil": 1967,
     "Comic": "Amazing Spider-Man #50"},
    {"Ad": "Rhino", "Cinsiyet": "Male", "Tur": "Mutate", "Tip": "Villain", "Kaynak": "Science", "Yil": 1966,
     "Comic": "Amazing Spider-Man #41"},
    {"Ad": "Shocker", "Cinsiyet": "Male", "Tur": "Human", "Tip": "Villain", "Kaynak": "Tech", "Yil": 1967,
     "Comic": "Amazing Spider-Man #46"},
    {"Ad": "Scorpion", "Cinsiyet": "Male", "Tur": "Mutate", "Tip": "Villain", "Kaynak": "Science", "Yil": 1964,
     "Comic": "Amazing Spider-Man #20"},
    {"Ad": "Hobgoblin", "Cinsiyet": "Male", "Tur": "Mutate", "Tip": "Villain", "Kaynak": "Science", "Yil": 1983,
     "Comic": "Amazing Spider-Man #238"},
    {"Ad": "Chameleon", "Cinsiyet": "Male", "Tur": "Human", "Tip": "Villain", "Kaynak": "Tech", "Yil": 1963,
     "Comic": "Amazing Spider-Man #1"},

    # --- YENİ EKLENEN VILLAINS (FARKLI & COOL OLANLAR) ---
    {"Ad": "Mr. Negative", "Cinsiyet": "Male", "Tur": "Mutate", "Tip": "Villain", "Kaynak": "Science", "Yil": 2007,
     "Comic":"Amazing Spider-Man (Vol 2) #546"},
    {"Ad": "The Spot", "Cinsiyet": "Male", "Tur": "Mutate", "Tip": "Villain", "Kaynak":"Accident", "Yil": 1984,
     "Comic": "Spectacular Spider-Man #98"},
    {"Ad": "Morlun", "Cinsiyet": "Male", "Tur": "Alien", "Tip": "Villain", "Kaynak": "Magic", "Yil": 2001,
     "Comic": "Amazing Spider-Man #30"},
    {"Ad": "Tombstone", "Cinsiyet": "Male", "Tur": "Mutate", "Tip": "Villain", "Kaynak": "Science", "Yil": 1988,
     "Comic": "Web of Spider-Man #36"},
    {"Ad": "Hammerhead", "Cinsiyet": "Male", "Tur": "Human", "Tip": "Villain", "Kaynak": "Science", "Yil": 1972,
     "Comic": "Amazing Spider-Man #113"},
    {"Ad": "Hydro-Man", "Cinsiyet": "Male", "Tur": "Mutate", "Tip": "Villain", "Kaynak": "Accident", "Yil": 1981,
     "Comic": "Amazing Spider-Man #212"},
    {"Ad": "Molten Man", "Cinsiyet": "Male", "Tur": "Mutate", "Tip": "Villain", "Kaynak": "Accident", "Yil": 1965,
     "Comic": "Amazing Spider-Man #28"},
    {"Ad": "Jackal", "Cinsiyet": "Male", "Tur": "Mutate", "Tip": "Villain", "Kaynak": "Science", "Yil": 1974,
     "Comic": "Amazing Spider-Man #129"},
    {"Ad": "Morbius", "Cinsiyet": "Male", "Tur": "Vampire", "Tip": "Villain", "Kaynak": "Science", "Yil": 1971,
     "Comic": "Amazing Spider-Man #101"},
    {"Ad": "Mephisto", "Cinsiyet": "Male", "Tur": "Demon", "Tip": "Villain", "Kaynak": "Magic", "Yil": 1968,
     "Comic": "Silver Surfer #3"},
    {"Ad": "Knull (Symbiote God)", "Cinsiyet": "Male", "Tur": "God", "Tip": "Villain", "Kaynak": "Magic", "Yil": 2018,
     "Comic": "Venom #3"},
    {"Ad": "Shriek", "Cinsiyet": "Female", "Tur": "Mutant", "Tip": "Villain", "Kaynak": "Genetic", "Yil": 1993,
     "Comic": "Spider-Man Unlimited #1"},
    {"Ad": "Scream", "Cinsiyet": "Female", "Tur": "Symbiote", "Tip": "Villain", "Kaynak": "Alien", "Yil": 1993,
     "Comic": "Venom: Lethal Protector #4"},
    {"Ad": "Alistair Smythe", "Cinsiyet": "Male", "Tur": "Human", "Tip": "Villain", "Kaynak": "Tech", "Yil": 1985,
     "Comic": "Amazing Spider-Man Annual #19"},
    {"Ad": "Silvermane", "Cinsiyet": "Male", "Tur": "Human", "Tip": "Villain", "Kaynak": "Tech", "Yil": 1969,
     "Comic": "Amazing Spider-Man #73"},
    {"Ad": "Tarantula", "Cinsiyet": "Male", "Tur": "Human", "Tip": "Villain", "Kaynak": "Tech", "Yil": 1974,
     "Comic": "Amazing Spider-Man #134"},
    {"Ad": "Kindred", "Cinsiyet": "Male", "Tur": "Demon", "Tip": "Villain", "Kaynak": "Magic", "Yil": 2018,
     "Comic": "Amazing Spider-Man #1"},

    # --- CIVILIANS (SİVİLLER) ---
    {"Ad": "Mary Jane Watson", "Cinsiyet": "Female", "Tur": "Human", "Tip": "Civilian", "Kaynak": "None", "Yil": 1966,
     "Comic": "Amazing Spider-Man #42"},
    {"Ad": "Gwen Stacy", "Cinsiyet": "Female", "Tur": "Human", "Tip": "Civilian", "Kaynak": "None", "Yil": 1965,
     "Comic": "Amazing Spider-Man #31"},
    {"Ad": "J.J. Jameson", "Cinsiyet": "Male", "Tur": "Human", "Tip": "Civilian", "Kaynak": "None", "Yil": 1963,
     "Comic": "Amazing Spider-Man #1"},
    {"Ad": "Aunt May", "Cinsiyet": "Female", "Tur": "Human", "Tip": "Civilian", "Kaynak": "None", "Yil": 1962,
     "Comic": "Amazing Fantasy #15"},
    {"Ad": "Uncle Ben", "Cinsiyet": "Male", "Tur": "Human", "Tip": "Civilian", "Kaynak": "None", "Yil": 1962,
     "Comic": "Amazing Fantasy #15"},
    {"Ad": "Harry Osborn", "Cinsiyet": "Male", "Tur": "Human", "Tip": "Civilian", "Kaynak": "None", "Yil": 1965,
     "Comic": "Amazing Spider-Man #31"},
    {"Ad": "Robbie Robertson", "Cinsiyet": "Male", "Tur": "Human", "Tip": "Civilian", "Kaynak": "None", "Yil": 1967,
     "Comic": "Amazing Spider-Man #51"},
    {"Ad": "Betty Brant", "Cinsiyet": "Female", "Tur": "Human", "Tip": "Civilian", "Kaynak": "None", "Yil": 1963,
     "Comic": "Amazing Spider-Man #4"},
    {"Ad": "Liz Allan", "Cinsiyet": "Female", "Tur": "Human", "Tip": "Civilian", "Kaynak": "None", "Yil": 1962,
     "Comic": "Amazing Fantasy #15"},
    {"Ad": "Ned Leeds", "Cinsiyet": "Male", "Tur": "Human", "Tip": "Civilian", "Kaynak": "None", "Yil": 1964,
     "Comic": "Amazing Spider-Man #18"},
    {"Ad": "Ben Urich", "Cinsiyet": "Male", "Tur": "Human", "Tip": "Civilian", "Kaynak": "None", "Yil": 1978,
     "Comic": "Daredevil #153"},
    {"Ad": "Jean DeWolff", "Cinsiyet": "Female", "Tur": "Human", "Tip": "Civilian", "Kaynak": "None", "Yil": 1976,
     "Comic": "Marvel Team-Up #48"},
    {"Ad": "Carlie Cooper", "Cinsiyet": "Female", "Tur": "Human", "Tip": "Civilian", "Kaynak": "None", "Yil": 2008,
     "Comic": "Amazing Spider-Man #545"},
]